package youtube

// TASK_TIMEOUT_MINUTES must be >= sum of (
//     YT_DLP_TIMEOUT_MINUTES
//     FFMPEG_TIMEOUT_MINUTES
//     CONVERT_TIMEOUT_SEC
//     EYED3_TIMEOUT_SEC
//     ATOMICPARSLEY_TIMEOUT_SEC
// )
const YT_DLP_TIMEOUT_MINUTES = 5
const FFMPEG_TIMEOUT_MINUTES = 5
const CONVERT_TIMEOUT_SEC = 60
const EYED3_TIMEOUT_SEC = 60
const ATOMICPARSLEY_TIMEOUT_SEC = 60
